version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@local-docker-testing-postgres-1/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=81HqDtbqAywKSOumSha3BhWNOdQ9hATsXK3OIdMTPWw=
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW_UID=50000
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AWS_ACCESS_KEY_ID=[access key id]
      - AWS_SECRET_ACCESS_KEY=[secret access key]
      - AWS_SESSION_TOKEN=[session token]

    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
    command: >
      bash -c 'airflow db migrate &&  airflow users create \
        --username ryan \
        --firstname ryan \
        --lastname newkirk \
        --role Admin \
        --email ryannewkirk2024@u.northwestern.edu \
        --password newkirk && 
      airflow webserver'

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@local-docker-testing-postgres-1/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=81HqDtbqAywKSOumSha3BhWNOdQ9hATsXK3OIdMTPWw=
      - AIRFLOW_UID=50000
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AWS_ACCESS_KEY_ID=[access key id]
      - AWS_SECRET_ACCESS_KEY=[secret access key]
      - AWS_SESSION_TOKEN=[session token]

    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
    command: bash -c 'airflow db migrate && airflow scheduler'
