# Use the official Python image
FROM python:latest




# Create a new user and set permissions
RUN useradd -m ryan


# Set ownership of the working directory
WORKDIR /app
RUN chown -R ryan /app




# Create a virtual environment
RUN python -m venv /venv

# Activate the virtual environment
ENV PATH="/venv/bin:${PATH}"

RUN pip install pandas sqlalchemy psycopg2-binary jupyter pyarrow matplotlib scipy boto3 bs4 requests scikit-learn


#switch to non-root user
USER ryan

# Optional: If you have notebooks to copy
COPY ./src/HW2.ipynb /app/HW2.ipynb

# Expose the Jupyter Notebook port
EXPOSE 8888

# Command to run Jupyter Notebook
#CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
CMD ["/bin/bash"]
